# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

#em vez de colocar os steps build aqui restore etc
# eu chamo meu arquivo docker q vai fazer tudo
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'luccascaron'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    buildContext: '.'
