version: '3.4'

services:
    projetoadv:
        image: ${DOCKER_REGISTRY-}teste_vai
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8081:80" 
        depends_on:
        - sqldata

    sqldata:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
        - SA_PASSWORD=Projeto#2024
        - ACCEPT_EULA=Y
        volumes:
        - c:\dados\volumes\mssql:/vaar/opt/mssql/data
        ports:
        - "1450:1433"
